"""
Physically-motivated synthetic Raman spectrum generator.

Peak positions are taken from the RRUFF database publications and peer-reviewed
mineralogy literature. Each mineral is represented by Lorentzian peaks at its
characteristic Raman shifts. Multiple spectra per mineral are generated by
adding realistic measurement variations (noise, baseline drift, intensity
scaling, minor calibration shift) to simulate real spectrometer output.

References
----------
- Lafuente et al. (2015) RRUFF project.
- Mao et al. (2019) Raman spectroscopy of minerals: a review.
- Frezzotti et al. (2012) Raman spectroscopy for fluid inclusion analysis.
- Standard references in: Handbook of Mineralogy, Anthony et al.
"""
import sys
import numpy as np
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from config import STANDARD_GRID, N_POINTS


# ---------------------------------------------------------------------------
# Mineral spectral database
# Peak format:  [(wavenumber_cm⁻¹, relative_intensity, half_width_cm⁻¹), ...]
# Relative intensity: 1.0 = strongest peak
# ---------------------------------------------------------------------------
MINERAL_PEAKS = {
    # ---- Carbonates --------------------------------------------------------
    "Calcite": [
        (156, 0.45, 8), (281, 0.70, 12), (713, 0.15, 8), (1085, 1.00, 9)
    ],
    "Dolomite": [
        (176, 0.40, 9), (299, 0.60, 11), (724, 0.20, 9), (1095, 1.00, 9)
    ],
    "Magnesite": [
        (211, 0.35, 9), (329, 0.55, 11), (738, 0.20, 9), (1094, 1.00, 10)
    ],
    "Siderite": [
        (185, 0.38, 9), (292, 0.55, 10), (727, 0.20, 8), (1083, 1.00, 9)
    ],
    "Aragonite": [
        (155, 0.50, 7), (207, 0.40, 8), (272, 0.45, 9), (704, 0.30, 8),
        (1085, 1.00, 8)
    ],
    "Rhodochrosite": [
        (178, 0.40, 8), (289, 0.55, 10), (726, 0.18, 8), (1086, 1.00, 9)
    ],
    "Smithsonite": [
        (205, 0.35, 9), (301, 0.50, 10), (728, 0.20, 8), (1085, 1.00, 9)
    ],
    "Cerussite": [
        (151, 0.40, 7), (237, 0.50, 8), (676, 0.25, 8), (1050, 1.00, 8)
    ],
    "Strontianite": [
        (154, 0.45, 7), (278, 0.55, 9), (705, 0.22, 8), (1069, 1.00, 8)
    ],
    "Witherite": [
        (137, 0.45, 7), (272, 0.50, 8), (706, 0.25, 8), (1059, 1.00, 8)
    ],

    # ---- Sulfates ----------------------------------------------------------
    "Gypsum": [
        (415, 0.45, 8), (493, 0.55, 7), (619, 0.30, 8), (671, 0.35, 8),
        (1008, 1.00, 7), (1138, 0.35, 8)
    ],
    "Anhydrite": [
        (417, 0.40, 8), (500, 0.50, 8), (608, 0.30, 9), (679, 0.35, 8),
        (1016, 1.00, 7), (1130, 0.30, 8)
    ],
    "Barite": [
        (461, 0.45, 7), (619, 0.35, 8), (647, 0.30, 8), (988, 1.00, 7),
        (1143, 0.30, 8)
    ],
    "Celestine": [
        (354, 0.45, 8), (461, 0.40, 7), (617, 0.35, 8), (998, 1.00, 7),
        (1130, 0.28, 8)
    ],
    "Anglesite": [
        (439, 0.40, 8), (584, 0.35, 8), (636, 0.30, 8), (975, 1.00, 7),
        (1137, 0.28, 8)
    ],
    "Alunite": [
        (295, 0.40, 9), (383, 0.45, 9), (643, 0.35, 8), (1004, 1.00, 8)
    ],
    "Jarosite": [
        (222, 0.45, 9), (357, 0.50, 9), (634, 0.40, 8), (1009, 1.00, 8)
    ],

    # ---- Silicates: Tectosilicates -----------------------------------------
    "Quartz": [
        (128, 0.90, 10), (207, 0.85, 12), (265, 0.45, 10), (355, 0.35, 10),
        (465, 1.00, 9), (697, 0.12, 10), (808, 0.10, 12)
    ],
    "Orthoclase": [
        (288, 0.55, 12), (513, 0.65, 14), (800, 0.35, 15), (1100, 0.45, 18)
    ],
    "Albite": [
        (293, 0.55, 12), (480, 0.60, 14), (807, 0.35, 14), (1105, 0.40, 18)
    ],
    "Microcline": [
        (290, 0.55, 12), (516, 0.60, 14), (803, 0.35, 14), (1101, 0.40, 18)
    ],
    "Sanidine": [
        (285, 0.50, 13), (512, 0.60, 14), (1102, 0.40, 18)
    ],
    "Labradorite": [
        (292, 0.50, 12), (484, 0.55, 13), (809, 0.35, 14), (1108, 0.40, 18)
    ],

    # ---- Silicates: Nesosilicates (Olivine group) --------------------------
    "Forsterite": [
        (222, 0.45, 10), (308, 0.50, 10), (432, 0.45, 10), (605, 0.40, 10),
        (826, 1.00, 9), (857, 0.80, 9)
    ],
    "Fayalite": [
        (200, 0.45, 11), (281, 0.50, 11), (379, 0.45, 11), (666, 0.40, 10),
        (820, 1.00, 10), (867, 0.70, 10)
    ],

    # ---- Silicates: Pyroxenes ----------------------------------------------
    "Enstatite": [
        (319, 0.55, 10), (340, 0.60, 10), (401, 0.35, 10), (680, 0.45, 10),
        (1012, 1.00, 10)
    ],
    "Diopside": [
        (325, 0.55, 10), (391, 0.60, 10), (666, 0.45, 10), (1013, 1.00, 10)
    ],
    "Augite": [
        (323, 0.50, 11), (388, 0.55, 11), (665, 0.45, 11), (1010, 1.00, 11)
    ],
    "Wollastonite": [
        (321, 0.50, 10), (411, 0.55, 10), (643, 0.40, 10), (973, 1.00, 10)
    ],

    # ---- Silicates: Garnets ------------------------------------------------
    "Grossular": [
        (352, 0.55, 10), (546, 0.60, 10), (877, 1.00, 10), (1003, 0.50, 11)
    ],
    "Almandine": [
        (350, 0.55, 10), (499, 0.60, 10), (914, 1.00, 10), (1039, 0.45, 11)
    ],
    "Pyrope": [
        (350, 0.55, 10), (508, 0.60, 10), (862, 1.00, 10), (1000, 0.45, 11)
    ],
    "Spessartine": [
        (351, 0.55, 10), (497, 0.60, 10), (921, 1.00, 10), (1029, 0.45, 11)
    ],

    # ---- Silicates: Phyllosilicates ----------------------------------------
    "Muscovite": [
        (262, 0.50, 12), (408, 0.65, 12), (700, 0.50, 14)
    ],
    "Phlogopite": [
        (190, 0.50, 12), (385, 0.65, 12), (680, 0.50, 14)
    ],
    "Biotite": [
        (179, 0.50, 13), (382, 0.60, 13), (676, 0.50, 14)
    ],
    "Talc": [
        (187, 0.50, 12), (365, 0.60, 12), (461, 0.55, 12), (678, 0.70, 12)
    ],
    "Kaolinite": [
        (144, 0.45, 10), (334, 0.55, 11), (431, 0.50, 11), (912, 1.00, 10)
    ],
    "Chlorite": [
        (353, 0.55, 12), (547, 0.50, 12), (678, 0.60, 12), (982, 0.90, 11)
    ],
    "Serpentine": [
        (230, 0.50, 12), (388, 0.65, 12), (692, 0.60, 13)
    ],

    # ---- Silicates: Nesosilicates ------------------------------------------
    "Topaz": [
        (340, 0.50, 10), (469, 0.65, 10), (737, 0.55, 10), (919, 1.00, 10)
    ],
    "Zircon": [
        (214, 0.40, 9), (357, 0.55, 9), (440, 0.45, 9), (975, 1.00, 9),
        (1010, 0.30, 10)
    ],
    "Kyanite": [
        (248, 0.45, 9), (375, 0.55, 10), (424, 0.50, 10), (966, 1.00, 9)
    ],
    "Andalusite": [
        (281, 0.40, 9), (456, 0.55, 9), (896, 1.00, 9)
    ],
    "Sillimanite": [
        (312, 0.50, 9), (490, 0.60, 9), (885, 1.00, 9)
    ],
    "Beryl": [
        (323, 0.50, 10), (397, 0.60, 10), (685, 0.55, 10), (1069, 1.00, 10)
    ],
    "Tourmaline": [
        (265, 0.45, 11), (371, 0.55, 11), (458, 0.50, 11), (1075, 1.00, 11)
    ],
    "Epidote": [
        (337, 0.50, 10), (399, 0.55, 10), (490, 0.45, 10), (576, 0.50, 10),
        (1100, 0.90, 12)
    ],

    # ---- Oxides ------------------------------------------------------------
    "Hematite": [
        (225, 0.60, 12), (291, 0.75, 12), (412, 1.00, 12), (499, 0.60, 12),
        (614, 0.55, 12)
    ],
    "Magnetite": [
        (310, 0.55, 18), (540, 0.65, 18), (668, 1.00, 18)
    ],
    "Goethite": [
        (245, 0.55, 12), (299, 1.00, 12), (388, 0.65, 12), (484, 0.55, 12),
        (550, 0.50, 12), (681, 0.45, 12)
    ],
    "Lepidocrocite": [
        (253, 0.55, 13), (349, 0.65, 13), (528, 0.60, 13), (651, 1.00, 13)
    ],
    "Rutile": [
        (143, 1.00, 10), (235, 0.45, 12), (447, 0.90, 10), (612, 0.60, 10)
    ],
    "Anatase": [
        (144, 1.00, 9), (197, 0.20, 11), (399, 0.80, 11), (515, 0.75, 10),
        (639, 0.55, 10)
    ],
    "Brookite": [
        (153, 0.60, 10), (172, 0.55, 10), (247, 0.65, 10), (636, 1.00, 10)
    ],
    "Corundum": [
        (379, 0.55, 10), (418, 0.60, 10), (432, 1.00, 10), (451, 0.50, 10),
        (578, 0.80, 10), (645, 0.60, 10), (751, 0.45, 10)
    ],
    "Spinel": [
        (408, 0.55, 12), (674, 1.00, 12), (771, 0.50, 12)
    ],
    "Chromite": [
        (455, 0.60, 14), (680, 1.00, 14)
    ],
    "Cassiterite": [
        (122, 0.60, 12), (473, 0.65, 12), (634, 1.00, 11), (776, 0.55, 12)
    ],
    "Periclase": [
        (400, 0.50, 30), (720, 1.00, 25)
    ],
    "Pyrolusite": [
        (320, 0.55, 14), (637, 1.00, 12)
    ],
    "Hausmannite": [
        (318, 0.50, 14), (370, 0.55, 14), (660, 1.00, 14)
    ],

    # ---- Sulfides ----------------------------------------------------------
    "Pyrite": [
        (343, 0.60, 9), (379, 1.00, 9), (430, 0.55, 10)
    ],
    "Marcasite": [
        (322, 0.65, 9), (391, 1.00, 9), (428, 0.55, 10)
    ],
    "Galena": [
        (96, 1.00, 8), (143, 0.65, 9), (189, 0.50, 9)
    ],
    "Sphalerite": [
        (276, 1.00, 9), (328, 0.50, 10)
    ],
    "Chalcopyrite": [
        (290, 0.55, 10), (318, 1.00, 10), (351, 0.60, 10)
    ],
    "Cinnabar": [
        (252, 0.70, 8), (283, 1.00, 8), (342, 0.50, 9)
    ],
    "Molybdenite": [
        (382, 1.00, 8), (408, 0.60, 8)
    ],
    "Arsenopyrite": [
        (341, 0.60, 9), (360, 1.00, 9)
    ],
    "Pyrrhotite": [
        (219, 0.55, 14), (282, 0.65, 14), (383, 1.00, 14)
    ],
    "Covellite": [
        (476, 0.60, 10), (500, 1.00, 10), (1090, 0.45, 14)
    ],
    "Pentlandite": [
        (265, 0.65, 12), (340, 1.00, 12)
    ],

    # ---- Phosphates --------------------------------------------------------
    "Apatite": [
        (432, 0.50, 10), (965, 1.00, 9), (1042, 0.55, 10), (1076, 0.45, 10)
    ],
    "Monazite": [
        (970, 1.00, 10), (1010, 0.35, 11)
    ],
    "Xenotime": [
        (988, 1.00, 10), (1010, 0.35, 11)
    ],
    "Vivianite": [
        (950, 1.00, 11), (1013, 0.60, 12)
    ],
    "Wavellite": [
        (455, 0.50, 11), (962, 1.00, 10), (1073, 0.45, 11)
    ],

    # ---- Halides & Oxalates -----------------------------------------------
    "Fluorite": [
        (322, 1.00, 12)
    ],
    "Halite": [
        (250, 1.00, 35)  # very broad, weak
    ],
    "Sylvite": [
        (268, 1.00, 18)
    ],

    # ---- Hydroxides --------------------------------------------------------
    "Gibbsite": [
        (321, 0.65, 10), (389, 0.80, 10), (965, 1.00, 10)
    ],
    "Brucite": [
        (280, 0.70, 12), (444, 1.00, 12)
    ],
    "Diaspore": [
        (287, 0.65, 10), (388, 0.75, 10), (988, 1.00, 9)
    ],
    "Boehmite": [
        (353, 0.60, 11), (449, 0.70, 11), (671, 1.00, 11)
    ],

    # ---- Carbonaceous minerals ---------------------------------------------
    "Graphite": [
        (1350, 0.60, 25), (1580, 1.00, 20), (2700, 0.55, 50)
    ],
    "Diamond": [
        (1332, 1.00, 5)
    ],

    # ---- Native elements ---------------------------------------------------
    "Sulfur": [
        (153, 0.65, 7), (219, 0.75, 7), (472, 1.00, 7)
    ],
    "Bismuth": [
        (70, 0.65, 8), (97, 1.00, 8)
    ],

    # ---- Tungstates / Molybdates -------------------------------------------
    "Scheelite": [
        (211, 0.45, 9), (401, 0.55, 9), (838, 1.00, 9)
    ],
    "Wolframite": [
        (195, 0.50, 10), (352, 0.60, 10), (720, 1.00, 10), (897, 0.75, 10)
    ],
    "Wulfenite": [
        (319, 0.50, 9), (770, 0.55, 9), (895, 1.00, 9)
    ],

    # ---- Carbonates (extra) ------------------------------------------------
    "Malachite": [
        (178, 0.45, 9), (352, 0.55, 9), (433, 0.50, 9), (1100, 1.00, 10)
    ],
    "Azurite": [
        (170, 0.40, 9), (400, 0.50, 9), (771, 0.45, 9), (1094, 1.00, 10)
    ],

    # ---- Zeolites ----------------------------------------------------------
    "Analcime": [
        (460, 0.55, 15), (1065, 1.00, 18)
    ],
    "Natrolite": [
        (380, 0.50, 14), (985, 1.00, 14), (1050, 0.60, 15)
    ],

    # ---- Miscellaneous industrial minerals ---------------------------------
    "Wollastonite_beta": [
        (324, 0.50, 10), (413, 0.55, 10), (646, 0.45, 10), (980, 1.00, 10)
    ],
    "Dolomite_ferrous": [
        (177, 0.40, 9), (300, 0.58, 11), (726, 0.20, 9), (1097, 1.00, 9)
    ],
}


# ---------------------------------------------------------------------------
# Spectrum synthesis
# ---------------------------------------------------------------------------

def lorentzian(x, center, amplitude, hwhm):
    """Lorentzian (Cauchy) lineshape."""
    return amplitude * hwhm ** 2 / ((x - center) ** 2 + hwhm ** 2)


def synthesize_spectrum(peaks, grid=STANDARD_GRID, rng=None):
    """
    Generate one Raman spectrum from a peak table.

    Each peak is (center_cm⁻¹, relative_amplitude, half_width_cm⁻¹).
    Random variations are applied to simulate measurement noise.
    """
    if rng is None:
        rng = np.random.default_rng()

    spectrum = np.zeros(len(grid))

    for center, amplitude, hwhm in peaks:
        # Small random calibration shift (±3 cm⁻¹)
        c = center + rng.uniform(-3, 3)
        # Random amplitude variation (±20%)
        a = amplitude * rng.uniform(0.80, 1.20)
        # Random width variation (±15%)
        w = hwhm * rng.uniform(0.85, 1.15)
        spectrum += lorentzian(grid, c, a, w)

    # Random polynomial baseline (fluorescence residual)
    if rng.random() < 0.8:
        t = np.linspace(0, 1, len(grid))
        b_amp = rng.uniform(0.0, 0.25)
        b_shape = rng.uniform(-1, 1)
        spectrum += b_amp * (t + b_shape * t ** 2)

    # Gaussian noise
    noise_level = rng.uniform(0.005, 0.03)
    spectrum += rng.normal(0.0, noise_level, len(grid))
    spectrum = np.clip(spectrum, 0.0, None)

    # Normalise
    peak_val = spectrum.max()
    if peak_val > 0:
        spectrum /= peak_val
    else:
        return None

    return spectrum.astype(np.float32)


# ---------------------------------------------------------------------------
# Dataset builder
# ---------------------------------------------------------------------------

def generate_dataset(
    data_dir="data",
    n_per_mineral=25,
    seed=42,
    min_grid_coverage=0.30,
):
    """
    Generate synthetic Raman training data and save to data/processed/.

    Parameters
    ----------
    n_per_mineral : int
        Number of synthetic spectra per mineral.
    min_grid_coverage : float
        Fraction of the standard grid that must be covered by at least one
        peak's support; discards minerals with peaks entirely outside range.
    """
    processed_dir = Path(data_dir) / "processed"
    processed_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(seed)

    valid_minerals = sorted(MINERAL_PEAKS.keys())

    print(f"Generating {n_per_mineral} spectra × {len(valid_minerals)} minerals "
          f"= {n_per_mineral * len(valid_minerals)} total spectra...")

    label_map = {name: i for i, name in enumerate(valid_minerals)}

    X_list, y_list = [], []

    for name in valid_minerals:
        peaks = MINERAL_PEAKS[name]
        label = label_map[name]
        generated = 0
        attempts = 0
        while generated < n_per_mineral and attempts < n_per_mineral * 5:
            attempts += 1
            s = synthesize_spectrum(peaks, rng=rng)
            if s is not None:
                X_list.append(s)
                y_list.append(label)
                generated += 1
        if generated < n_per_mineral:
            print(f"  WARNING: only {generated}/{n_per_mineral} spectra for {name}")

    X = np.array(X_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.int64)

    np.save(processed_dir / "X.npy", X)
    np.save(processed_dir / "y.npy", y)

    labels_df = pd.DataFrame({
        "label": range(len(valid_minerals)),
        "mineral": valid_minerals,
    })
    labels_df.to_csv(processed_dir / "label_map.csv", index=False)

    # Reference spectra — noiseless mean-like spectrum (3 samples averaged)
    ref = np.zeros((len(valid_minerals), N_POINTS), dtype=np.float32)
    for name in valid_minerals:
        peaks = MINERAL_PEAKS[name]
        idx = label_map[name]
        samples = [synthesize_spectrum(peaks, rng=rng) for _ in range(3)]
        samples = [s for s in samples if s is not None]
        if samples:
            mean_s = np.mean(samples, axis=0)
            peak_val = mean_s.max()
            ref[idx] = mean_s / peak_val if peak_val > 0 else mean_s

    np.save(processed_dir / "reference_spectra.npy", ref)

    print(f"\nSynthetic dataset ready:")
    print(f"  Spectra: {len(X)}")
    print(f"  Mineral classes: {len(valid_minerals)}")
    print(f"  Grid: {STANDARD_GRID[0]:.0f}-{STANDARD_GRID[-1]:.0f} cm-1 "
          f"({N_POINTS} points)")

    return X, y, label_map


if __name__ == "__main__":
    generate_dataset()
